version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "groupsky"

  - package-ecosystem: "docker"
    directory: "/docker/traefik"
    schedule:
      interval: "daily"
    reviewers:
      - "groupsky"

  - package-ecosystem: "docker"
    directory: "/docker/traefik-whoami"
    schedule:
      interval: "daily"
    reviewers:
      - "groupsky"
