version: '3.1'
services:

  traefik:
    build: docker/traefik
    restart: on-failure
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --entrypoints.http.address=:${TRAEFIK_HTTP_PORT}
      - --entrypoints.https.address=:${TRAEFIK_HTTPS_PORT}
      - --log.level=DEBUG
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=${INGRESS_NETWORK}
    networks:
      - ${INGRESS_NETWORK}
    ports:
      - "${TRAEFIK_HTTP_PORT}:${TRAEFIK_HTTP_PORT}"
      - "${TRAEFIK_HTTPS_PORT}:${TRAEFIK_HTTPS_PORT}"
    volumes:
      # TODO secure the access
      - /var/run/docker.sock:/var/run/docker.sock

  traefik-whoami:
    build: docker/traefik-whoami
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-whoami.entrypoints=http"
      - "traefik.http.routers.traefik-whoami.rule=Host(`${TRAEFIK_WHOAMI_DOMAIN}`)"
    networks:
      - ${INGRESS_NETWORK}
