version: '3.1'
services:

  traefik:
    build: docker/traefik
    restart: on-failure
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --certificatesResolvers.default.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesResolvers.default.acme.caServer=${TRAEFIK_ACME_CA_SERVER}
      - --certificatesResolvers.default.acme.storage=/acme/acme.json
      - --certificatesResolvers.default.acme.httpChallenge.entryPoint=http
      - --entrypoints.http.address=:${TRAEFIK_HTTP_PORT}
      - --entrypoints.https.address=:${TRAEFIK_HTTPS_PORT}
      - --log.level=${TRAEFIK_LOG_LEVEL}
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=${INGRESS_NETWORK}
    networks:
      - ${INGRESS_NETWORK}
    ports:
      - "${TRAEFIK_HTTP_PORT}:${TRAEFIK_HTTP_PORT}"
      - "${TRAEFIK_HTTPS_PORT}:${TRAEFIK_HTTPS_PORT}"
    volumes:
      - ${TRAEFIK_DATA_ACME_PATH}:/acme
      # TODO secure the access
      - /var/run/docker.sock:/var/run/docker.sock

  traefik-whoami:
    build: docker/traefik-whoami
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-whoami.entrypoints=http, https"
      - "traefik.http.routers.traefik-whoami.rule=Host(`${TRAEFIK_WHOAMI_DOMAIN}`)"
      - "traefik.http.routers.traefik-whoami.tls.certResolver=default"
    networks:
      - ${INGRESS_NETWORK}
